{
 "title": "ASCO AWS CodeBuild",
 "description": "Visualize AWS CodeBuild metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "projectname",
    "label": "ProjectName",
    "query": "dimension_values($region,AWS/CodeBuild,BuildDuration,ProjectName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Builds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ProjectName": "$projectname" },
     "metricName": "Builds",
     "namespace": "AWS/CodeBuild",
     "region": "default",
     "statistics": [ "SampleCount" ]
    }
   ]
  },
  {
   "title": "Builds /Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "ProjectName": "$projectname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Builds",
     "namespace": "AWS/CodeBuild",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "SampleCount" ]
    }
   ]
  },
  {
   "title": "Build Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "ProjectName": "$projectname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FailedBuilds",
     "namespace": "AWS/CodeBuild",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "ProjectName": "$projectname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SucceededBuilds",
     "namespace": "AWS/CodeBuild",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Durations/Build",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "ProjectName": "$projectname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Duration",
     "namespace": "AWS/CodeBuild",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "ProjectName": "$projectname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Builds",
     "namespace": "AWS/CodeBuild",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}