{
 "title": "ASCO Jira",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "label": "project", "query": { "query": "label_values(project)" } }
  ]
 },
 "panels": [
  {
   "title": "Jira Issues",
   "type": "stat",
   "description": "Jira issues count grouped by issue type",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (jira_issues{issue_type=~\"Epic|Story|Bug|Task|Sub-task\",project=~\"$project\"}) by (issue_type, project)",
     "legendFormat": "{{issue_type}}"
    }
   ]
  },
  {
   "title": "Status_Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (jira_issues{status=~\"To Do|In Progress|Done\",project=~\"$project\"}) by (status, project)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top Assignees",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3,sum(jira_issues{assignee!~\"None\", project=~\"$project\"}) by(assignee, project))",
     "legendFormat": "{{assignee}}"
    }
   ]
  }
 ]
}