{
 "title": "Demo ASCO Lib",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "envi", "label": "Envi", "query": "cloudwatch" },
   {
    "name": "applicationname",
    "label": "ApplicationName",
    "query": "appsync, common-core, page-layout, search-components, ui-components, ui-composites, ui-containers"
   }
  ]
 },
 "panels": [
  {
   "title": "Jira",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jira Issues",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (jira_issues{issue_type=~\"Epic|Story|Bug|Task|Sub-task\",project=~\"ATD\"}) by (issue_type, project)",
       "legendFormat": "{{issue_type}}"
      }
     ]
    },
    {
     "title": "Status_Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (jira_issues{status=~\"To Do|In Progress|Done\",project=~\"ATD\"}) by (status, project)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Status_Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(3,sum(jira_issues{assignee!~\"None\", project=~\"ATD\"}) by(assignee, project))",
       "legendFormat": "{{assignee}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GitHub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "repository",
   "collapsed": true,
   "panels": [
    {
     "title": "commits",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "options": { "gitRef": "master", "query": "" }, "owner": "ascogit", "repository": "ASCO.applications" }
     ]
    },
    {
     "title": "Tags",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "options": { "gitRef": "$branch", "query": "" }, "owner": "ascogit", "repository": "ASCO.applications" }
     ]
    },
    {
     "title": "Releases",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "options": { "gitRef": "$branch", "query": "" }, "owner": "ascogit", "repository": "ASCO.applications" }
     ]
    },
    {
     "title": "Pull Requests Created",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "options": { "gitRef": "$branch", "query": "", "timeField": 1 }, "owner": "ascogit", "repository": "ASCO.applications" }
     ]
    },
    {
     "title": "Active Pull Requests",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "options": { "gitRef": "$branch", "query": "is:open", "timeField": 3 }, "owner": "ascogit", "repository": "ASCO.applications" }
     ]
    },
    {
     "title": "PR average open time",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "options": { "gitRef": "$branch", "query": "", "timeField": 0 }, "owner": "ascogit", "repository": "ASCO.applications" }
     ]
    },
    {
     "title": "Issues",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "options": { "gitRef": "$branch", "query": "", "timeField": 0 }, "owner": "ascogit", "repository": "ASCO.applications" }
     ]
    },
    {
     "title": "Active Issues",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "options": { "gitRef": "$branch", "query": "is:open", "timeField": 0 }, "owner": "ascogit", "repository": "ASCO.applications" }
     ]
    },
    {
     "title": "Issues Avg. Open Time (Closed issues)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "options": { "gitRef": "$branch", "query": "is:open", "timeField": 0 }, "owner": "ascogit", "repository": "ASCO.applications" }
     ]
    }
   ]
  },
  {
   "title": "SonarCloud",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "applicationname",
   "collapsed": true,
   "panels": [
    {
     "title": "ASCO.applications.lib.$applicationname",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonar_bugs{key=~\"ASCO.applications.lib.$applicationname$\"}",
       "legendFormat": "Bugs"
      },
      {
       "expr": "sonar_security_remediation_effort  {key=~\"ASCO.applications.lib.$applicationname$\"}",
       "legendFormat": "security"
      },
      {
       "expr": "sonar_security_rating{key=~\"ASCO.applications.lib.$applicationname$\"}",
       "legendFormat": "Rating"
      },
      {
       "expr": "sonar_duplicated_lines{key=~\"ASCO.applications.lib.$applicationname$\"}        ",
       "legendFormat": "Duplications"
      },
      {
       "expr": "sonar_line_coverage{key=~\"ASCO.applications.lib.$applicationname$\"}",
       "legendFormat": "lines_Coverage"
      },
      {
       "expr": "sonar_code_smells{key=~\"ASCO.applications.lib.$applicationname$\"}  ",
       "legendFormat": "Code Smells"
      }
     ]
    }
   ]
  },
  { "title": "CodeBuild", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "${applicationname}-build ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "applicationname",
   "collapsed": true,
   "panels": [
    {
     "title": "Total builds",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Build/Day",
       "dimensions": { "ProjectName": "sandbox-$applicationname-build" },
       "metricName": "Builds",
       "namespace": "AWS/CodeBuild",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Builds / Day",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Build Count",
       "dimensions": { "ProjectName": "sandbox-$applicationname-build" },
       "metricName": "Builds",
       "namespace": "AWS/CodeBuild",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "statistics": [ "SampleCount" ]
      }
     ]
    },
    {
     "title": "Duration / Build",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "dimensions": { "ProjectName": "sandbox-$applicationname-build" },
       "metricName": "Duration",
       "namespace": "AWS/CodeBuild",
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      },
      {
       "dimensions": { "ProjectName": "sandbox-$applicationname-build" },
       "metricName": "Builds",
       "namespace": "AWS/CodeBuild",
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Build Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "SucceededBuilds",
       "dimensions": { "ProjectName": "sandbox-$applicationname-build" },
       "metricName": "SucceededBuilds",
       "namespace": "AWS/CodeBuild",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      },
      {
       "alias": "FaliedBuilds",
       "dimensions": { "ProjectName": "sandbox-$applicationname-build" },
       "metricName": "FailedBuilds",
       "namespace": "AWS/CodeBuild",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      }
     ]
    }
   ]
  },
  {
   "title": "${applicationname}-deploy-live-deploy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "applicationname",
   "collapsed": true,
   "panels": [
    {
     "title": "Total builds",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Build/Day",
       "dimensions": {
        "ProjectName": "sandbox-${applicationname}-deploy-live-deploy"
       },
       "metricName": "Builds",
       "namespace": "AWS/CodeBuild",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Builds / Day",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Build Count",
       "dimensions": {
        "ProjectName": "sandbox-${applicationname}-deploy-live-deploy"
       },
       "metricName": "Builds",
       "namespace": "AWS/CodeBuild",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "statistics": [ "SampleCount" ]
      }
     ]
    },
    {
     "title": "Duration / Build",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "dimensions": {
        "ProjectName": "sandbox-${applicationname}-deploy-live-deploy"
       },
       "metricName": "Duration",
       "namespace": "AWS/CodeBuild",
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      },
      {
       "dimensions": {
        "ProjectName": "sandbox-${applicationname}-deploy-live-deploy"
       },
       "metricName": "Builds",
       "namespace": "AWS/CodeBuild",
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Build Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "SucceededBuilds",
       "dimensions": {
        "ProjectName": "sandbox-${applicationname}-deploy-live-deploy"
       },
       "metricName": "SucceededBuilds",
       "namespace": "AWS/CodeBuild",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      },
      {
       "alias": "FaliedBuilds",
       "dimensions": {
        "ProjectName": "sandbox-${applicationname}-deploy-live-deploy"
       },
       "metricName": "FailedBuilds",
       "namespace": "AWS/CodeBuild",
       "queryMode": "Metrics",
       "region": "us-east-1",
       "statistics": [ "Sum" ]
      }
     ]
    }
   ]
  }
 ]
}