{
 "title": "ASCO SonarCloud",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "project", "label": "Projects", "query": { "query": "label_values(sonar_bugs, key)" } }
  ]
 },
 "panels": [
  { "title": "Bugs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bugs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_bugs{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Security Rating",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "repeat": "project",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Violations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonar_violations{key=~\"^$project\"}",
       "legendFormat": "{{key}}"
      }
     ]
    }
   ]
  },
  { "title": "Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Reliability Rating",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 74 },
   "repeat": "project",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 },
   "collapsed": true
  },
  {
   "title": "Code Smells",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 140 },
   "repeat": "project",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonar_sqale_rating{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Covergae", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 205 } },
  {
   "title": "Line Coverage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 206 },
   "repeat": "project",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sonar_line_coverage{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  }
 ]
}