{
 "title": "ASCO Services Dashboard",
 "time": { "from": "now-80d", "to": "now" },
 "templating": {
  "list": [
   { "name": "envi", "label": "Envi", "query": "cloudwatch" },
   {
    "name": "services",
    "label": "Services",
    "query": "accountelasticsync, content, contentrepstream, dynamiccontent, dynamo, embedfields, esconfigs, helloworld, importsheridan, importzoomorphix, mdmvalidateaddress, meeting, message, pinnacleordersync, podcastprocessor, productactivation, profile, surveymonkey, utiladdlookup, validateaddress, xmlparser"
   }
  ]
 },
 "panels": [
  {
   "title": "Jira",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jira Project Summary",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jira_issues{issue_type=~\"Epic\",project=~\"ADP\"}) by (issue_type, project)",
       "legendFormat": "{{issue_type}}"
      },
      {
       "expr": "sum(jira_issues{issue_type=~\"Story\",project=~\"ADP\"}) by (issue_type, project)",
       "legendFormat": "{{issue_type}}"
      },
      {
       "expr": "sum (jira_issues{issue_type=~\"Task\",project=~\"ADP\"}) by (issue_type, project)",
       "legendFormat": "{{issue_type}}"
      },
      {
       "expr": "sum(jira_issues{issue_type=~\"Bug\",project=~\"ADP\"}) by (issue_type, project)",
       "legendFormat": "{{issue_type}}"
      }
     ]
    },
    {
     "title": "Issue Status",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jira_issues{status=~\"Open\",project=~\"ADP\"}) by (status, project)",
       "legendFormat": "{{status}}"
      },
      {
       "expr": "sum(jira_issues{status=~\"On Hold\",project=~\"ADP\"}) by (status, project)",
       "legendFormat": "{{status}}"
      },
      {
       "expr": "sum(jira_issues{status=~\"Closed\",project=~\"ADP\"}) by (status, project)",
       "legendFormat": "{{status}}"
      },
      {
       "expr": "sum(jira_issues{status=~\"Work Started\",project=~\"ADP\"}) by (status, project)",
       "legendFormat": "{{status}}"
      },
      {
       "expr": "sum(jira_issues{status=~\"In QA\",project=~\"ADP\"}) by (status, project)",
       "legendFormat": "{{status}}"
      },
      {
       "expr": "sum(jira_issues{status=~\"Back to Dev\",project=~\"ADP\"}) by (status, project)",
       "legendFormat": "{{status}}"
      },
      {
       "expr": "sum(jira_issues{status=~\"Ready for Development\",project=~\"ADP\"}) by (status, project)",
       "legendFormat": "{{status}}"
      },
      {
       "expr": "sum(jira_issues{status=~\"PM Review\",project=~\"ADP\"}) by (status, project)",
       "legendFormat": "{{status}}"
      },
      {
       "expr": "sum(jira_issues{status=~\"Grooming\",project=~\"ADP\"}) by (status, project)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Top Assignees",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(4,sum(jira_issues{assignee!~\"None\", status=~\"Open\", project=~\"ADP\"}) by (assignee, status))",
       "legendFormat": "{{assignee}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GitHub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "repository",
   "collapsed": true,
   "panels": [
    {
     "title": "Commits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "options": { "gitRef": "main", "query": "" }, "owner": "ascogit", "repository": "ASCO.services" }
     ]
    },
    {
     "title": "Pull Requests Created",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      { "options": { "gitRef": "$branch", "query": "", "timeField": 1 }, "owner": "ascogit", "repository": "ASCO.services" },
      { "options": { "gitRef": "$branch", "query": "is:open", "timeField": 3 }, "owner": "ascogit", "repository": "ASCO.applications" }
     ]
    },
    {
     "title": "Top Contributors",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "targets": [
      { "options": { "query": " " }, "owner": "ascogit", "repository": "ASCO.services" }
     ]
    },
    {
     "title": " PR Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "targets": [
      { "owner": "ascogit", "repository": "ASCO.services" }
     ]
    }
   ]
  },
  {
   "title": "SonarCloud-ASCO.applications.app.$applicationname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "applicationname"
  },
  {
   "title": "Bugs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_bugs{key=~\"ASCO.services.$services\"}",
     "legendFormat": "Bugs"
    }
   ]
  },
  {
   "title": "Security Hotspots",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_security_hotspots{key=~\"ASCO.services.$services\"}",
     "legendFormat": "Security Hotspots"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_new_vulnerabilities{key=~\"ASCO.services.$services\"}",
     "legendFormat": "vulnerabilities"
    }
   ]
  },
  {
   "title": "Duplications",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"ASCO.services.$services\"} ",
     "legendFormat": "Duplications"
    }
   ]
  },
  {
   "title": "Code Coverage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"ASCO.services.$services\"}",
     "legendFormat": "Line Coverage"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_code_smells{key=~\"ASCO.services.$services\"}",
     "legendFormat": "Code Smells"
    }
   ]
  },
  {
   "title": "${envi}-${applicationname}-template",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "applicationname"
  },
  {
   "title": "Total builds",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Builds",
     "dimensions": { "ProjectName": "$envi-$services-templates" },
     "metricName": "Builds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Build Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "SucceededBuilds",
     "dimensions": { "ProjectName": "$envi-$services-templates" },
     "metricName": "SucceededBuilds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "FailedBuilds",
     "dimensions": { "ProjectName": "$envi-$services-templates" },
     "metricName": "FailedBuilds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "Total Builds",
     "dimensions": { "ProjectName": "$envi-$services-templates" },
     "metricName": "Builds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Duration / Build",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "ProjectName": "$envi-$services-templates" },
     "metricName": "Duration",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Build Associated PRs",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expression": "fields @timestamp, @message, @logStream\n| filter @message like \"HEAD is now\"\n| sort @timestamp desc\n| limit 100",
     "logGroupNames": [
      "/aws/codebuild/$envi-$services-templates"
     ],
     "namespace": "AWS/CodeBuild",
     "queryMode": "Logs",
     "region": "us-east-1"
    },
    {
     "expression": "fields @timestamp,@message \n| filter @message like \"HEAD is now\"\n| parse @message \"HEAD is now at * Merge pull request * *\" as id, id2, id3\n| sort @timestamp desc\n| limit 10000",
     "logGroupNames": [
      "/aws/codebuild/$envi-$services-templates"
     ],
     "namespace": "AWS/CodeBuild",
     "queryMode": "Logs",
     "region": "us-east-1"
    },
    {
     "expression": "fields @timestamp, @message \n| filter @message like \"Phase complete: BUILD State\"\n| parse @message \"* * * * * * * *\" as id, id2, id3, id4, id5, id6, id7, id8\n| limit 10000",
     "logGroupNames": [
      "/aws/codebuild/$envi-$services-templates"
     ],
     "namespace": "AWS/CodeBuild",
     "queryMode": "Logs",
     "region": "us-east-1"
    },
    {
     "expression": "fields @timestamp, @message \n| filter @message like \"Phase complete: PRE_BUILD State\"\n| parse @message \"* * * * * * * *\" as id, id2, id3, id4, id5, id6, id7, id8\n| limit 10000",
     "logGroupNames": [
      "/aws/codebuild/$envi-$services-templates"
     ],
     "namespace": "AWS/CodeBuild",
     "queryMode": "Logs",
     "region": "us-east-1"
    },
    {
     "expression": "fields @timestamp, @message \n| filter @message like \"Phase complete: POST_BUILD State\"\n| parse @message \"* * * * * * * *\" as id, id2, id3, id4, id5, id6, id7, id8\n| limit 10000",
     "logGroupNames": [
      "/aws/codebuild/$envi-$services-templates"
     ],
     "namespace": "AWS/CodeBuild",
     "queryMode": "Logs",
     "region": "us-east-1"
    }
   ]
  },
  {
   "title": "${envi}-${applicationname}-deploy-promotion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "applicationname"
  },
  {
   "title": "Total Deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Build/Day",
     "dimensions": {
      "ProjectName": "$envi-$services-deploy-promotion"
     },
     "metricName": "Builds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Deployment Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "SucceededBuilds",
     "dimensions": {
      "ProjectName": "$envi-$services-deploy-promotion"
     },
     "metricName": "SucceededBuilds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "FailedBuilds",
     "dimensions": {
      "ProjectName": "$envi-$services-deploy-promotion"
     },
     "metricName": "FailedBuilds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "Total Builds",
     "dimensions": {
      "ProjectName": "$envi-$services-deploy-promotion"
     },
     "metricName": "Builds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Duration / Deployment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": {
      "ProjectName": "$envi-$services-deploy-promotion"
     },
     "metricName": "Duration",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  }
 ]
}