{
 "title": "ASCO Velocity Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "envi", "label": "Envi", "query": "cloudwatch" },
   {
    "name": "applicationname",
    "label": "ApplicationName",
    "query": "dashboard, hub, meeting-program-view, meeting-registration"
   }
  ]
 },
 "panels": [
  { "title": "Jira", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jira Project Summary",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jira_issues{issue_type=~\"Epic\",project=~\"ADP\"}) by (issue_type, project)",
     "legendFormat": "{{issue_type}}"
    },
    {
     "expr": "sum(jira_issues{issue_type=~\"Story\",project=~\"ADP\"}) by (issue_type, project)",
     "legendFormat": "{{issue_type}}"
    },
    {
     "expr": "sum (jira_issues{issue_type=~\"Task\",project=~\"ADP\"}) by (issue_type, project)",
     "legendFormat": "{{issue_type}}"
    },
    {
     "expr": "sum(jira_issues{issue_type=~\"Bug\",project=~\"ADP\"}) by (issue_type, project)",
     "legendFormat": "{{issue_type}}"
    }
   ]
  },
  {
   "title": "Issue Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jira_issues{status=~\"Open\",project=~\"ADP\"}) by (status, project)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(jira_issues{status=~\"On Hold\",project=~\"ADP\"}) by (status, project)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(jira_issues{status=~\"Closed\",project=~\"ADP\"}) by (status, project)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(jira_issues{status=~\"Work Started\",project=~\"ADP\"}) by (status, project)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(jira_issues{status=~\"In QA\",project=~\"ADP\"}) by (status, project)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(jira_issues{status=~\"Back to Dev\",project=~\"ADP\"}) by (status, project)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(jira_issues{status=~\"Ready for Development\",project=~\"ADP\"}) by (status, project)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(jira_issues{status=~\"PM Review\",project=~\"ADP\"}) by (status, project)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(jira_issues{status=~\"Grooming\",project=~\"ADP\"}) by (status, project)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top Assignees",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(4,sum(jira_issues{assignee!~\"None\", status=~\"Open\", project=~\"ADP\"}) by (assignee, status))",
     "legendFormat": "{{assignee}}"
    }
   ]
  },
  { "title": "GitHub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "repository" },
  {
   "title": "Commits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "options": { "gitRef": "master", "query": "" }, "owner": "ascogit", "repository": "ASCO.applications" }
   ]
  },
  {
   "title": "Pull Requests Created",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "options": { "gitRef": "$branch", "query": "", "timeField": 1 }, "owner": "ascogit", "repository": "ASCO.applications" },
    { "options": { "gitRef": "$branch", "query": "is:open", "timeField": 3 }, "owner": "ascogit", "repository": "ASCO.applications" }
   ]
  },
  {
   "title": "Top Contributors",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "targets": [
    { "options": { "query": " " }, "owner": "ascogit", "repository": "ASCO.applications" }
   ]
  },
  {
   "title": "SonarCloud-ASCO.applications.app.$applicationname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "applicationname"
  },
  {
   "title": "Bugs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_bugs{key=~\"ASCO.applications.app.$applicationname$\"}",
     "legendFormat": "Bugs"
    }
   ]
  },
  {
   "title": "Security",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_security_remediation_effort  {key=~\"ASCO.applications.app.$applicationname$\"}",
     "legendFormat": "security"
    }
   ]
  },
  {
   "title": "Rating",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_security_rating{key=~\"ASCO.applications.app.$applicationname$\"}",
     "legendFormat": "rating"
    }
   ]
  },
  {
   "title": "Duplications",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_duplicated_lines_density{key=~\"ASCO.applications.app.$applicationname$\"} ",
     "legendFormat": "Duplications"
    }
   ]
  },
  {
   "title": "Code Coverage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_coverage{key=~\"ASCO.applications.app.$applicationname$\"}",
     "legendFormat": "Line Coverage"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonar_code_smells{key=~\"ASCO.applications.app.$applicationname$\"}",
     "legendFormat": "Code Smells"
    }
   ]
  },
  {
   "title": "${envi}-${applicationname}-build ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "applicationname"
  },
  {
   "title": "Total builds",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Builds",
     "dimensions": { "ProjectName": "$envi-$applicationname-build" },
     "metricName": "Builds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Build Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "SucceededBuilds",
     "dimensions": { "ProjectName": "$envi-$applicationname-build" },
     "metricName": "SucceededBuilds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "FailedBuilds",
     "dimensions": { "ProjectName": "$envi-$applicationname-build" },
     "metricName": "FailedBuilds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "Total Builds",
     "dimensions": { "ProjectName": "$envi-$applicationname-build" },
     "metricName": "Builds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Duration / Build",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "ProjectName": "$envi-$applicationname-build" },
     "metricName": "Duration",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "${envi}-${applicationname}-deploy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "applicationname"
  },
  {
   "title": "Total Deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Build/Day",
     "dimensions": {
      "ProjectName": "$envi-$applicationname-deploy-live-deploy"
     },
     "metricName": "Builds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Deployment Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "SucceededBuilds",
     "dimensions": {
      "ProjectName": "$envi-$applicationname-deploy-live-deploy"
     },
     "metricName": "SucceededBuilds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "FailedBuilds",
     "dimensions": {
      "ProjectName": "$envi-$applicationname-deploy-live-deploy"
     },
     "metricName": "FailedBuilds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "Total Builds",
     "dimensions": {
      "ProjectName": "$envi-$applicationname-deploy-live-deploy"
     },
     "metricName": "Builds",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Duration / Deployment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": {
      "ProjectName": "$envi-$applicationname-deploy-live-deploy"
     },
     "metricName": "Duration",
     "namespace": "AWS/CodeBuild",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  }
 ]
}